version: '3.2'

services:
    db:
        image: postgres:10.3
        container_name: brasilio_postgres
        env_file: env
        ports:
            - "39001:5432"
        volumes:
            - ./docker/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
            - ./docker/postgresql/data:/var/lib/postgresql/data
        command: -c "config_file=/etc/postgresql/postgresql.conf"
    graph_db:
        image: neo4j:3.3
        container_name: brasilio_neo4j
        environment:
            - NEO4J_AUTH=none
            - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
            - NEO4J_dbms_connector_bolt_address=0.0.0.0:7687
            - NEO4J_dbms_connectors_default__listen__address=0.0.0.0:7474
        ports:
            - "39002:7474"
            - "39003:7687"
        volumes:
            - ./docker/neo4j/data/:/data/

    django:
        container_name: brasilio_django
        build:
            context: ../..
            dockerfile: compose/dev/Dockerfile
        restart: always
        depends_on:
            - db
            - graph_db
        env_file: env
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        links:
            - db
            - graph_db
